---
name: TBM VyOS Automated Builds

on:
  workflow_dispatch:
    inputs:
      build-image:
        description: Build the `vyos-build` container image?
        default: "Yes"
        options:
          - "Yes"
          - "No"
        required: true
        type: choice
      patch-string:
        description: Patch version? (leave blank for none)
        required: false
        type: string
      run-smoketests:
        description: Run smoketests on the ISO?
        default: "Yes"
        options:
          - "Yes"
          - "No"
        required: true
        type: choice
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create-version-number:
    name: Create version number
    outputs:
      version: ${{ env.VERSION }}
      vyos-build-commit: ${{ env.VYOS_BUILD_COMMIT }}
      vyos-1x-commit: ${{ env.VYOS_1X_COMMIT }}
    runs-on: ubuntu-24.04
    steps:
      - id: date-format
        name: Run `date` and format
        run: |
          set -ex
          echo "VERSION=$(date +'%Y%m')" >> "$GITHUB_ENV"
      - id: patch-string
        if: ${{ inputs.patch-string != '' }}
        name: Add patch string
        run: |
          set -ex
          echo "VERSION=$VERSION-${{ inputs.patch-string }}" >> "$GITHUB_ENV"
      - name: "Fetch the `vyos-build` repository"
        uses: actions/checkout@v4.2.2
        with:
          path: vyos-build
          ref: current
          repository: vyos/vyos-build
      - name: Get last `vyos-build` commit
        run: |
          set -ex
          echo "VYOS_BUILD_COMMIT=$(git --no-pager log --pretty=format:%h --max-count=1)" >> "$GITHUB_ENV"
        working-directory: vyos-build
      - name: "Fetch the `vyos-1x` repository"
        uses: actions/checkout@v4.2.2
        with:
          path: vyos-1x
          ref: current
          repository: vyos/vyos-1x
      - name: Get last `vyos-1x` commit
        run: |
          set -ex
          echo "VYOS_1X_COMMIT=$(git --no-pager log --pretty=format:%h --max-count=1)" >> "$GITHUB_ENV"
        working-directory: vyos-1x
  build-push-container:
    if: ${{ inputs.build-image == 'Yes' }}
    name: Build and push `vyos-build` container image
    needs: [create-version-number]
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/vyos-build-docker.yaml
  create-runner:
    if: ${{ !cancelled() }}
    name: Create self-hosted runner
    needs: [build-push-container, create-version-number]
    runs-on: ubuntu-latest
    steps:
      - name: Create runner (ISO)
        uses: MattKobayashi/tailscale-qemu-runner-action@v1.5.6
        with:
          gh-api-token: ${{ secrets.GH_API_TOKEN }}
          gha-runner-apt-mirror: http://mirror.overthewire.com.au/ubuntu/
          gha-runner-labels: iso
          gha-runner-tz: Australia/Brisbane
          ssh-host: 100.102.37.118
          ssh-user: matthew
          ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          ts-tag: ci
  build-iso:
    container:
      credentials:
        password: ${{ secrets.github_token }}
        username: ${{ github.actor }}
      env:
        TZ: Australia/Brisbane
      image: ${{ vars.REGISTRY }}/${{ vars.REPO_OWNER }}/vyos-build:current
      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
    defaults:
      run:
        shell: bash
    if: ${{ !cancelled() }}
    name: Build and smoketest ISO
    needs: [build-push-container, create-version-number]
    permissions:
      contents: write
      packages: read
    runs-on: iso
    steps:
      - id: fetch-vyos-build
        name: Fetch the `vyos-build` repository
        run: |
          set -ex
          git clone --depth=1 https://github.com/vyos/vyos-build.git
      - id: remount-workdir
        name: Remount the work directory
        run: |
          set -ex
          mount -i -o remount,exec,dev /__w/
      - id: change-os-release
        name: Change the value of `os-release`
        run: |
          set -ex
          sed -i 's/NAME="VyOS"/NAME="TBM VyOS"/' scripts/image-build/build-vyos-image
        working-directory: vyos-build
      - id: build-iso
        name: Build the VyOS ISO
        run: |
          set -ex
          sudo make clean
          sudo ./build-vyos-image \
            --architecture amd64 \
            --build-by 'tbm-vyos@tech.bymatt.au' \
            --build-comment 'Please direct all support queries to support@tech.bymatt.au' \
            --build-type release \
            --version ${{ needs.create-version-number.outputs.version }} \
            --custom-apt-entry 'deb http://deb.debian.org/debian bookworm non-free-firmware' \
            --custom-apt-entry 'deb http://deb.debian.org/debian-security bookworm-security non-free-firmware' \
            --custom-apt-entry 'deb http://deb.debian.org/debian bookworm-updates non-free-firmware' \
            --custom-package intel-microcode \
            --custom-package amd64-microcode \
            --custom-package vyos-1x-smoketest \
            generic
        working-directory: vyos-build
      - id: run-smoketests
        if: ${{ inputs.run-smoketests == 'Yes' }}
        name: Run smoketests
        run: |
          set -ex
          sudo make test
        working-directory: vyos-build
      - id: rename-iso
        name: Rename the VyOS ISO
        run: |
          set -ex
          ORIG_NAME=$(ls vyos-*.iso)
          mv $ORIG_NAME tbm-$ORIG_NAME
        working-directory: vyos-build/build
      - id: draft-release
        name: Create a new draft release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: false
          artifactContentType: application/x-iso9660-image
          artifactErrorsFailBuild: true
          artifacts: "vyos-build/build/tbm-vyos-*.iso"
          body: |
            Build log: https://github.com/MattKobayashi/tbm-vyos/actions/runs/${{ github.run_id }}

            Latest included `vyos-build` commit: https://github.com/vyos/vyos-build/commit/${{ needs.create-version-number.outputs.vyos-build-commit }}
            Commits to `vyos-build` since this build: https://github.com/vyos/vyos-build/compare/${{ needs.create-version-number.outputs.vyos-build-commit }}...current

            Latest included `vyos-1x` commit: https://github.com/vyos/vyos-1x/commit/${{ needs.create-version-number.outputs.vyos-1x-commit }}
            Commits to `vyos-1x` since this build: https://github.com/vyos/vyos-1x/compare/${{ needs.create-version-number.outputs.vyos-1x-commit }}...current
          draft: true
          name: TBM VyOS ${{ needs.create-version-number.outputs.version }}
          omitDraftDuringUpdate: true
          tag: ${{ needs.create-version-number.outputs.version }}
