---
name: Build `vyos-build` container image

on:
  workflow_call:

jobs:
  build-and-push-container:
    name: Build and push `vyos-build` container
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Fetch the `vyos-build` repository
        id: fetch-vyos-build
        uses: actions/checkout@v4
        with:
          repository: 'MattKobayashi/vyos-build'
          ref: 'current'
          path: 'vyos-build'
      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: vyos-build/docker
          push: true
          tags: ${{ vars.REGISTRY }}/${{ vars.REPO_OWNER }}/vyos-build:current
