---
name: Build `vyos-build` container image

on:
  workflow_call:

jobs:
  build-and-push-container:
    name: Build and push `vyos-build` container
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Fetch the `vyos-build` repository
        id: fetch-vyos-build
        uses: actions/checkout@v4.1.7
        with:
          repository: 'vyos/vyos-build'
          ref: 'current'
          path: 'vyos-build'
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.REPO_OWNER }}/vyos-build
          tags: type=raw,value=current
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: vyos-build/docker
          push: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
