---
name: Build `vyos-build` container image

on:
  workflow_call:
    secrets:
      GH_API_TOKEN:
        required: true
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_SECRET:
        required: true
  workflow_dispatch:

jobs:
  build-push-container:
    name: Build and push
    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
      - id: fetch-vyos-build
        name: Fetch the `vyos-build` repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: vyos-build
          ref: current
          repository: vyos/vyos-build
      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          password: ${{ secrets.github_token }}
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
      - id: meta
        name: Extract Docker metadata
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.REPO_OWNER }}/vyos-build
          tags: type=raw,value=current
      - name: Build and push Docker image
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          context: vyos-build/docker
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
