---
name: Build and push `vyos-build` container image

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-push-container:
    name: Build and push `vyos-build` container image
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["registry-mirror:5000"]
            [registry."registry-mirror:5000"]
              http = true
          driver-opts: |
            network=mattflix
      - name: Fetch the `vyos-build` repository
        id: fetch-vyos-build
        uses: actions/checkout@v4.2.0
        with:
          repository: vyos/vyos-build
          ref: current
          path: vyos-build
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.REPO_OWNER }}/vyos-build
          tags: type=raw,value=current
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: vyos-build/docker
          push: ${{ github.event.pull_request.merged == 1 }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
