---
name: vyos-build container image

on:
  workflow_call:
    secrets:
      GH_API_TOKEN:
        required: true
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_SECRET:
        required: true
  workflow_dispatch:

jobs:
  create-runner:
    name: Create runner
    runs-on: ubuntu-latest
    steps:
      - name: Create self-hosted runner (container)
        uses: MattKobayashi/tailscale-qemu-runner-action@v1.4.0
        with:
          gh-api-token: ${{ secrets.GH_API_TOKEN }}
          gha-runner-apt-mirror: http://au.archive.ubuntu.com/ubuntu/
          gha-runner-labels: container
          gha-runner-tz: Australia/Brisbane
          ssh-host: 100.102.37.118
          ssh-user: matthew
          ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          ts-tag: ci
  build-push-container:
    name: Build and push
    runs-on: container
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Fetch the `vyos-build` repository
        id: fetch-vyos-build
        uses: actions/checkout@v4.2.2
        with:
          repository: vyos/vyos-build
          ref: current
          path: vyos-build
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.REPO_OWNER }}/vyos-build
          tags: type=raw,value=current
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: vyos-build/docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
