---
name: VyOS 1.3 Autobuild

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - blog_1.3

jobs:
  build-iso:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    permissions:
      contents: write

    container:
      image: vyos/vyos-build:equuleus
      env:
        TZ: Australia/Brisbane
      options: --privileged

    steps:
      - name: Clone the `vyos-build` repository
        id: clone-upstream
        run: |
          set -eux
          git clone -b equuleus --single-branch https://github.com/vyos/vyos-build

      - name: Get the latest upstream tag
        id: get-upstream-tag
        working-directory: vyos-build
        run: |
          set -eux
          echo "latest=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - name: Get the commit ID for the latest upstream tag
        id: get-tag-commit-id
        working-directory: vyos-build
        run: |
          set -eux
          echo "commit=$(git rev-list --max-count=1 tags/${{ steps.get-upstream-tag.outputs.latest }})" >> "$GITHUB_OUTPUT"

      # - name: Reset the repository to the latest tag's commit ID
      #   id: reset-repo-to-tag
      #   working-directory: vyos-build
      #   run: |
      #     set -eux
      #     git reset --hard ${{ steps.get-tag-commit-id.outputs.commit }}

      - name: Configure the VyOS build
        id: configure-build
        working-directory: vyos-build
        run: |
          set -eux
          ./configure --architecture amd64 --build-by vyos-autobuild@tech.bymatt.au --build-type release --version ${{ steps.get-upstream-tag.outputs.latest }}

      - name: Build the VyOS ISO
        id: build-iso
        working-directory: vyos-build
        run: |
          set -eux
          make iso

      - name: Create a new release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          name: "VyOS ${{ steps.get-upstream-tag.outputs.latest }}"
          tag: "${{ steps.get-upstream-tag.outputs.latest }}"
          artifacts: "vyos-build/build/vyos-${{ steps.get-upstream-tag.outputs.latest }}-amd64.iso"
          artifactContentType: application/x-iso9660-image
          artifactErrorsFailBuild: true
          body: |
            Last included `vyos-build` commit: https://github.com/vyos/vyos-build/commit/${{ steps.get-tag-commit-id.outputs.commit }}

            Commits to `vyos-build` since this build: https://github.com/vyos/vyos-build/compare/${{ steps.get-upstream-tag.outputs.latest }}...equuleus

            Commits to `vyos-1x` since this build: https://github.com/vyos/vyos-1x/compare/${{ steps.get-upstream-tag.outputs.latest }}...equuleus
          draft: true
          allowUpdates: false
          omitDraftDuringUpdate: true
